title: Nikita Korobkov
description: B.S. Student with software development experience
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
logo: /userpic.jpg


gems:
  - jekyll-mentions
